stages:
  - test
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-2
  BUCKET_NAME: playtest.silvergryphongames.com

linting:
  stage: test
  before_script:
    - ruby -v
    - which ruby
    - gem install mdl
    - pip install proselint
  script:
    - mdl -s markdown-style.rb manuscript/
    - proselint manuscript/*.md

pandoc:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y pandoc texlive
  script:
    - sed -i "s/DATE/`date +'%B %e, %Y'`/g" front-page.md
    - mkdir -p ./build
    - pandoc --version
    - pandoc --template=mysteries.latex -f markdown -s -o ./build/mysteriesofabrokenworld.pdf front-page.md manuscript/*.md metadata.yaml
  artifacts:
    paths:
      - ./build

deploy to s3:
  image: "python:latest"
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 cp ./build/ s3://${BUCKET_NAME}/ --recursive --exclude "*" --include "*.pdf"
  environment:
    name: production
    url: http://${BUCKET_NAME}/
  only:
    - master
